# JDBCの接続設定
dbcp2.jdbc:
  # ドライバー
  driver-class-name: com.mysql.jdbc.Driver
  # MySQL
  url: jdbc:mysql://localhost:3306/moviedb?characterEncoding=UTF-8
  username: root
  password: mK_naDaru80_benten
  # コネクションプール
  initial-size: 1
  max-idle: 3
  min-idle: 1
  
  # mybatisの設定
  mybatis:
    mapper-locations: classpath:com/example/springDemo/repository/mybatis/*.xml
